### ISSUE TITLE
转到国际区后，商店的结算货币是美元

### ISSUE THREAD

**Issue by srjanese** [CMoyuer/PicoAreaHelper#1]
目前这个版本转到国际区后，商店的结算货币是美元，通过CMD代码转到日区后，商店的结算货币依然是美元，不是都说日区的价格便宜嘛！所以有没有办法转到国际区后，商店的结算是日元。

**Comment by CMoyuer** [comment]
实测一体机区域跟结算货币无关，换到日区一样显示19.9美元。想低价购买VD只能手机装一个国际Pico助手再挂日本节点购买

**Comment by srjanese** [comment]
刚刚写完问题就试了下科学上网，确实如此。感谢回答！
