### ISSUE TITLE
Fitness/Explore/Friends/*/Browser still Chinese versions. (fixed Avatar)

### ISSUE THREAD

**Issue by jarrard** [CMoyuer/PicoAreaHelper#2]
Updated Info:

~~Fixed Avatar App by cleaning the cache which must have had Chinese data in it causing problems.~~

~~Fitness, Explore(Home), Friends, Browser, are/were still stuck as Chinese version.~~

~~Remaining Issues:~~
~~Global Packages found. Fitness and Friends app need to the global APK reinstalled upon device report.~~

~~**Note Events option is exclusive to Chinese market.**~~

Solution to convert headsets to full global found by owomushi in the end, so guess I was wrong.  Didn't think he'd find a way.
Here is his latest video about it. 
MY HEADSET needed the NON-OEM update zip so if the normal one isn't found (update unavailable) then try the non-oem zips.

https://www.youtube.com/watch?v=Kzwrj4lXxVc

Thread closed.

**Comment by FrasSmith** [comment]
Can I add Pico Video to the list of apps that remain as Chinese versions.

**Comment by ooBadgeroo** [comment]
I have exactly same issue with fitness, friends and user avatar.

**Comment by jarrard** [comment]
Yeah was thinking that there must be some more ADB commands needed to switch these other apps to the UK server center and language in some cases.  My guess as to why Avatar reports no network is because its trying to connect to the China servers still...

**Comment by FrasSmith** [comment]
I think what it needs is for somebody with a global Pico 4 to extract the relevant APK files from their unit and then add them to this repo and scripts. Or to at least share them so that they can be added.

**Comment by jarrard** [comment]
Easy to do in debug mode. Probably a couple config files we can swap in and out to fix things, I doubt they differ much.

Maybe someone can ZIP up the entire Pico-4 UK filesystem so we can pick it apart (they'd need to ensure no extra apps are installed).

**Comment by CMoyuer** [comment]
If want to switch area completely, we may need a complete offline upgrade package.
Operation sequence:
1. Open factory settings with ADB
`adb shell am start -n com.picovr.factorytest/com.picovr.factorytest.setting.PicoSettingMainActivity`
2. Switch the area outside of CN
3. Install the offline upgrade package

**Comment by FrasSmith** [comment]
Maybe when they release 5.2 in November they'll make the offline upgrade package available.

**Comment by ooBadgeroo** [comment]
I'm worried that upgrading to 5.2 will wipe my entire 5.1 installation and reset to Chinese version.

Is there  some way of backing up completely what I have and restoring it if that happens?

**Comment by FrasSmith** [comment]
> If want to switch area completely, we may need a complete offline upgrade package. Operation sequence:
> 
> 1. Open factory settings with ADB
>    `adb shell am start -n com.picovr.factorytest/com.picovr.factorytest.setting.PicoSettingMainActivity`
> 2. Switch the area outside of CN
> 3. Install the offline upgrade package

As 5.2 is out now, do you think this technique might work for an online update? I'm wary of installing the update in case it reverses the switch to global store etc.

**Comment by FrasSmith** [comment]
> If want to switch area completely, we may need a complete offline upgrade package. Operation sequence:
> 
> 1. Open factory settings with ADB
>    `adb shell am start -n com.picovr.factorytest/com.picovr.factorytest.setting.PicoSettingMainActivity`
> 2. Switch the area outside of CN
> 3. Install the offline upgrade package

As 5.2 is out now, do you think this technique might work for an online update? I'm wary of installing the update in case it reverses the switch to global store etc.

**Comment by jarrard** [comment]
I might get time to try the update tonight. Been busy with my main PC lately as I prepare for a complete system upgrade (downgrading to older machine to sell off the newer parts, breaking my windows install etc... all the fun stuff)

My main PC is just a jumble of guts on the table here, hehe... I should be able to use it to fix any PICO-4 region resets if the update does that however.

**Comment by ooBadgeroo** [comment]
I checked System Update s in the headset and it still shows 5.1 with no updates available?

I searched for an offline 5.2 update to download, but I can't find it anywhere?

Any help to update this Chinese Pico 4 to 5.2 would be appreciated.

 I have my Region set to U.S.

**Comment by ooBadgeroo** [comment]
Well, the 5.2.1 update appeared in my headset under system update.

I ran it and it installed fine.

Although, I still have the apps EXERCISE (running in Chinese), FRIENDS (won't load at all) and USER area avatar setting are says there is a network error when starting.

Any ideas the to get a complete OFFLINE Package of 5.2.1 so I can replace and fix those apps?

**Comment by jarrard** [comment]
Yeah same did the update last night. 

I think the issue may be that the region of those apps is set wrong still, needs a different command. I do not know what.

**Comment by jarrard** [comment]
If anyone finds something then please post here. 

Maybe it's a matter of copying the PICO4 drive and editing a few config/xml files somewhere to fix those others apps.  

My guess as to why updates don't touch those apps is because Pico has yet to issue any fixes or changes to these components yet and perhaps the old Chinese files remain until then.

**Comment by ooBadgeroo** [comment]
Jarrad...

I agree ... I'm still trying to locate those same apps.

I think your guess may be right, but it is frustrating to have them still in Chinese and/or some not working at all.

Thanks for your feedback....

**Comment by jarrard** [comment]
I went through the process of installing the Matrix/Store/UserCenter apks again and noticed for a short period of time the English version of some apps appeared such as browser, but after a minute they were removed.  I looked at the saved files on the pico and noticed two web browser app config folders, one was a global version I believe as I loaded it briefing and it was all English, no Chinese symbols.

I'm starting to lean towards needing to ROM update the PICO with the UK/English Pico OS rom and NOT just APK install apps.. It's clear the OS is the issue and that is what needs to be flashed.   APK's don't touch the OS version.  Even updates just install update APK's I think.

Need UK Pico OS Rom File and Instructions to Flash it.

**Comment by ooBadgeroo** [comment]
Sorry Jarred. 

I don’t have access to anything that would do that, nor do I know how to flash it.

I noticed that I am still running version 5.2.1, and yet version 5.2.2 has been released available for update in some countries, however, I don’t have that showing for my location in the US.

You may be right about the prom thing, but what a pain in the ass. Caveat emptor for anyone buying from China the Pico 4 headset version they’re flogging right now.

**Comment by jarrard** [comment]
If someone with the global version ardreno dumped the rom then that be a good first step.

**Comment by ooBadgeroo** [comment]
I doubt we'll be able to find someone who is able. or willing to do that.

But.. it would be great if we could...

**Comment by jarrard** [comment]
Going to work through this with ADB force uninstall Chinese packages.  

There is going to be a way and I'll figure it out. Also the android settings app does work.

ATM it seems installing global apps causes it to delete them for some reason (script). So maybe removing Chinese Browser first will help. (as example)

Quote surprised there isn't a HORDE of people in this situation but I guess MOST people tossed their P4 or sent it back. 

Current package list for PICO-4

```
package:com.sohu.inputmethod.sogou.car
package:com.pvr.configuration
package:com.android.cts.priv.ctsshim
package:com.bytedance.os.feedback
package:com.qualcomm.qti.qcolor
package:com.android.internal.display.cutout.emulation.corner
package:com.Novelab.Spheres_Global
package:com.android.internal.display.cutout.emulation.double
package:com.solas.vr
package:com.android.dynsystem
package:com.pvr.pvrfit
package:com.android.providers.media
package:com.picovr.settings
package:com.pvr.shortcut
package:com.qti.service.colorservice
package:com.qualcomm.qti.gpudrivers.sm8250.api29
package:com.android.internal.systemui.navbar.gestural_wide_back
package:com.qualcomm.qti.simcontacts
package:com.android.wallpapercropper
package:com.pvr.pxrnotification
package:com.pvr.verify
package:com.android.theme.color.cinnamon
package:com.bytedance.pico.matrix
package:com.picovr.gallery_local
package:com.pvr.handle.upgrade
package:com.android.theme.icon_pack.rounded.systemui
package:com.android.documentsui
package:com.android.externalstorage
package:com.android.htmlviewer
package:com.android.companiondevicemanager
package:com.qualcomm.qti.qms.service.connectionsecurity
package:com.android.providers.downloads
package:com.android.networkstack.inprocess
package:com.android.theme.icon_pack.rounded.android
package:com.picoxr.ControllerTest_Phoenix_v2
package:com.qualcomm.qti.performancemode
package:VirtualDesktop.Android
package:com.bytedance.newFT
package:com.android.theme.icon_pack.circular.themepicker
package:vendor.qti.iwlan
package:dxidev.openhiddensettings
package:android.qvaoverlay.common
package:com.picovr.activitycenter
package:com.android.pacprocessor
package:com.android.simappdialog
package:android.overlay.common
package:com.picovr.tobvrusercenter
package:com.android.internal.display.cutout.emulation.tall
package:com.android.modulemetadata
package:com.android.certinstaller
package:com.android.theme.color.black
package:com.pvr.tobhome
package:com.pvr.adapter
package:com.android.theme.color.green
package:com.android.theme.color.ocean
package:com.pvr.scenemanager
package:com.android.theme.color.space
package:org.codeaurora.bluetooth
package:com.picovr.vrusercenter
package:com.android.internal.systemui.navbar.threebutton
package:com.pvr.home
package:android
package:com.qualcomm.wfd.service
package:com.android.theme.icon_pack.rounded.launcher
package:com.android.egg
package:com.android.mtp
package:com.android.backupconfirm
package:com.picovr.enterpriseassistant
package:com.picovr.wing.videoplayer
package:com.android.internal.systemui.navbar.twobutton
package:com.picovr.provision
package:com.android.statementservice
package:com.android.hotspot2
package:android.overlay.target
package:com.bytedance.os.slardar
package:com.android.settings.intelligence
package:com.pico.provider.settings
package:com.pico.xr.openxr_runtime
package:com.android.internal.systemui.navbar.gestural_extra_wide_back
package:com.pvr.filemanager
package:com.qualcomm.qti.dynamicddsservice
package:com.android.providers.settings
package:os.teatracker
package:com.pvr.vrdisplay
package:com.android.sharedstoragebackup
package:com.android.theme.icon_pack.filled.settings
package:com.picovr.logcatchsettings
package:com.android.webview
package:com.android.inputdevices
package:com.android.bips
package:com.pvr.developmentsettings
package:com.android.theme.icon_pack.circular.settings
package:com.DefaultCompany.ETUnity
package:com.android.musicfx
package:com.android.theme.icon.teardrop
package:android.ext.shared
package:com.android.onetimeinitializer
package:com.android.keychain
package:com.qti.snapdragon.qdcm_ff
package:com.android.printservice.recommendation
package:com.picovr.factorytest
package:com.android.theme.icon_pack.filled.systemui
package:android.ext.services
package:com.picovr.initserver
package:com.android.phone.overlay.common
package:com.android.carrierconfig.overlay.common
package:com.android.systemui.overlay.common
package:com.ss.android.ttvr
package:com.android.server.telecom.overlay.common
package:com.android.localtransport
package:com.android.packageinstaller
package:com.android.carrierdefaultapp
package:com.dsi.ant.server
package:com.android.theme.font.notoserifsource
package:com.android.theme.icon_pack.filled.android
package:com.android.proxyhandler
package:com.pico.browser
package:com.iflytek.inputmethod.pico
package:com.android.theme.icon_pack.circular.systemui
package:com.android.inputmethod.latin
package:com.pvr.version
package:com.pico.guardian
package:com.android.managedprovisioning
package:com.pvr.assistanthmd
package:com.picovr.guide
package:com.picovr.share
package:com.picovr.store
package:com.pvr.appmanager
package:com.bytedance.pico.screencapture
package:com.pvr
package:com.pvr.vrshell
package:com.picovr.picostreamassistant
package:com.android.theme.icon.squircle
package:com.android.storagemanager
package:com.android.bookmarkprovider
package:com.android.settings
package:com.pvr.seethrough.setting
package:com.qualcomm.qti.lpa
package:com.qualcomm.qti.uim
package:com.android.theme.icon_pack.filled.launcher
package:com.android.networkstack.permissionconfig
package:com.pvr.LightSeethrough
package:com.android.cts.ctsshim
package:com.pvr.tobservice
package:com.android.theme.icon_pack.circular.launcher
package:com.qualcomm.qti.uimGbaApp
package:com.picovr.keyguard
package:com.android.vpndialogs
package:com.android.shell
package:com.android.theme.icon_pack.filled.themepicker
package:com.android.wallpaperbackup
package:com.android.providers.blockednumber
package:com.picopui.im
package:com.pvr.lanserver
package:com.android.providers.userdictionary
package:com.qualcomm.qti.seccamservice
package:com.android.internal.systemui.navbar.gestural
package:com.picovr.init.overlay
package:com.pvr.avatareditor
package:com.android.location.fused
package:com.android.theme.color.orchid
package:com.android.systemui
package:com.android.wifiauthorize
package:com.android.theme.color.purple
package:com.android.bluetoothmidiservice
package:com.picovr.mdm
package:com.qualcomm.qti.poweroffalarm
package:com.qti.ltebc
package:com.android.permissioncontroller
package:com.pvr.tobactivate
package:com.android.traceur
package:com.picovr.picovrlib.cvcontroller
package:com.android.bluetooth
package:com.qualcomm.timeservice
package:com.qualcomm.embms
package:com.picovr.nativeshell
package:com.picovr.updatesystem
package:com.android.captiveportallogin
package:com.android.theme.icon.roundedrect
package:com.pvr.picocast
package:com.android.internal.systemui.navbar.gestural_narrow_back
package:com.android.theme.icon_pack.rounded.settings
package:com.android.bluetooth.overlay.common
package:com.android.theme.icon_pack.circular.android
```

**Comment by jarrard** [comment]
Apps we are interested in listed below (Pico apps that may or may not be configured correctly) 
I'm going to manually uninstall any Chinese defaulted apps and try the APK installs again.

These lists are for my own sanity to go through but also if you know for sure if a app here is the WRONG language or version then let me know.

As you can see lots are belonging to PICO. It's likely some of these apps SHOULD NOT be installed on global version and are providing meta data to CCP or doing stuff like uninstalling global apps automatically.

### Below are know apps
com.pvr.picocast
com.pico.browser (this is Chinese version)
com.pvr.pvrfit (Chinese!)
com.pvr.avatareditor (this is one for sure we know is broken)
com.iflytek.inputmethod.pico  (Chinese!)
com.sohu.inputmethod.sogou.car (chinese?)
com.picovr.store (changes to global fine)
com.picovr.activitycenter (Events is in Chinese!)
com.picopui.im (Friends is in Chinese!)


### Below are critical components or Unknown
com.pvr.home (Unknown, thought was Explore, uninstall does nothing)
com.pvr.tobhome (Unknown, thought was Explore, uninstall does nothing)
com.picovr.mdm
com.picovr.nativeshell
com.picovr.updatesystem
com.picovr.picovrlib.cvcontroller
com.picovr.init.overlay
com.picovr.share
com.picovr.guide
com.picovr.initserver
com.picovr.factorytest
com.picovr.keyguard
com.picovr.logcatchsettings
com.picovr.provision
com.picovr.wing.videoplayer
com.picovr.enterpriseassistant
com.picovr.tobvrusercenter
com.picovr.picostreamassistant
com.picovr.vrusercenter

com.bytedance.pico.screencapture
com.bytedance.os.slardar
com.bytedance.os.feedback
com.bytedance.newFT
com.bytedance.pico.matrix

com.pvr.vrshell
com.pvr
com.pvr.tobactivate
com.pvr.lanserver
com.pvr.tobservice
com.pvr.LightSeethrough
com.pvr.seethrough.setting
com.pvr.appmanager
com.pvr.assistanthmd
com.pico.guardian
com.pvr.version
com.pvr.developmentsettings
com.pvr.vrdisplay
com.pvr.filemanager
com.pico.xr.openxr_runtime
com.pico.provider.settings
com.pvr.configuration
com.picovr.settings
com.pvr.shortcut
com.pvr.pxrnotification
com.pvr.verify
com.picovr.gallery_local
com.pvr.handle.upgrade
com.picoxr.ControllerTest_Phoenix_v2
com.pvr.adapter
com.pvr.scenemanager

**Comment by jarrard** [comment]
Success #1 Avatar Editor now correct version. Can select and use avatars.  

Now to fix the half a dozen other stuck in Chinese/CCP Server apps.

**Comment by ooBadgeroo** [comment]
That’s awesome Jarrard

How did you get it working?

**Comment by jarrard** [comment]
> How did you get it working?

Well that is the issue. I'm not 100% sure, I think all I did was use the Android settings thing and cleared local data for that one. Unfortunately this trick doesn't appear to work for other apps stuck in Chinese. _(Avatar app wasn't in chinese, just had bad local data)_

**Comment by ooBadgeroo** [comment]
Can you  explain to me how are use the android app and clear what you describe?

it would be great if I could at least get the avatar setting to work.

**Comment by jarrard** [comment]
Load up SideQuest, search for Open Settings, install that.
I believe that is what I used to browse the apps (Avatar one) and cleared cache and storage on it.

You can also do it via adb command like how the bat scripts do it for the user center.
adb shell pm clear com.pvr.avatareditor  (this should work)

The issue we are facing now is I believe there are several other APK's needed from the global headset to fix Explore/Friends/Events/Fitness App... basically I'm thinking those did not come with the provided apks on this github.

If only our Chinese speaking friends could understand the issue here and help out because it seems they have access to these files (understandable since some likely work in Pico fabs making these things for global)

**Comment by jarrard** [comment]
It looks like the Explore app resets the user files again if you uninstall it (pvr.home). Unlike the other apps such as Friends and Events where if you uninstall those for the user they do not reinstall and thus icons don't work.

These apk apps are on the internal ROM of the PICO-4 and can't fully be uninstalled _(that is for special android flashing apps)_ thus if the app is in Chinese on the ROM, reinstalling it will just cause wrong language version.

This is why we need the APK's of the global versions which is easy enough to obtain with a tool like App Inspector (you can get apk from web). 

**The issue;** need a good samaritan to download the internal ROM apks onto a USB and upload them here. There will likely be 5 or more needed to fix most the issues.

If you find someone who can help, bring them here. It's pretty trivial to dump APK's from the headset ROM and HOPEFULLY by installing those with adb on our Chinese headsets it will fix these problems _(will need to clear Storage/Cache of each app for it tp take, IE. Like what was needed for Avatar app)_

**Comment by jarrard** [comment]
I got App Inspector from the below link and installed the APK via ADB, when loaded up you can scroll through the apps installed (there are many) and then it will give you the address to the internal ROM APK location, you can DOWNLOAD this from headset to a location accessible via USB or something.

https://m.apkpure.com/app-inspector/com.ubqsoft.sec01

If you have friends with PICO-4 global; now's the time to contact them.  Unfortunately I don't.

Opened thread up here: https://www.reddit.com/r/PicoXR/comments/za7u2j/request_for_apk_dump_from_global_user_just_1_app/

**Comment by ooBadgeroo** [comment]
Jarrad...

Thank you for all your valuable posts and idea in this topic.

I will load up side quest as you suggest and try to fix the Avatar issue.

I'm not as technical as you, but I did discover that I'm able to see my Pico 4 appear as a drive under Windows 11 when plugged in. It shows me all the folders on my current headset.  Is that of use to you if I copy any folders you need to my desktop?

Unfortunately I don't know anyone who has a Pico 4 Global either. :(

Again, thank you for all your efforts trying to solve our joint problem,

Regards,
Doug

**Comment by jarrard** [comment]
Got an Official response from PICO and they said we have Chinese version. It cannot be converted to global _(a lie since we already done most of that already)_ because it be some security issue... basically they said, yeah we don't give a crap, see ya! 

Typical corp response. Updating Ardrino ROM to Global version doesn't break security, you can provide the compiled rom. Mobile phone companies have been doing it for over a decade!  

This is a ANDROID device, it has android APK and software all through it as per package list above.

The bogus response has certainly put PICO down on the list of future VR vendors I'd buy from. They could have said they don't currently have a solution instead of lying and making up nonsense....

**Comment by ooBadgeroo** [comment]
Jarrad

Yes, this worked fine and I now have a functioning User Center again.

adb shell pm clear com.pvr.avatareditor (this should work)

Appreciate the tip...

Now, if we could just get other apps running in English Global, that would be great.

By the way, my headset just performed a Dec 1, 2022 update to v5.2.7

Regards,
Doug

**Comment by jarrard** [comment]
Found some progress here:  https://www.youtube.com/watch?v=fVUgZseBwqg **(I recommend avoid the discord!)**

However friends app don't work for me, and the events and picofit is chinese still.

So still some work to be done.

**Comment by ooBadgeroo** [comment]
Jarrard

thanks for the video! I see it’s new and I wondered if you would actually run it against your headset? My headset has been updated to 5.2.7 so I don’t know if it will mess up if I try to run the script. What do you think?

I wish there was a way I could back up the entire headset someplace, and then restore it if this doesn’t work.

**Comment by jarrard** [comment]
Yes well I have everything working except no APK for Events app yet (activitycenter) and when you reboot the headset the Fitness and Friends app resets back to Chinese...

So need to figure out those bugs, well doubt I will but maybe Mushi dude will... 

As for backup, yeah factory reset is only option. 

Also Uninstalling Apps can prevent them from being able to install again until factory reset... bit weird.

**Comment by jarrard** [comment]
It should be ok but I had to Factory reset mine as I uninstalled couple things and it didn't like that (removed the app for good). 
There could be a ADB command to fix that sort of thing, like install app for user:0 or something but I couldn't figure it out.

I can run the script and technically it works but my Win11 doesn't like the %% expressions so I just did the commands manually myself.

**Comment by hirosichen** [comment]
Thanks for the software. My Pico 4 is global version. I can run your software to have Chinese version store. But I could not login my Chinese user (which is mobile phone number). How to solve the issue? Thanks!

**Comment by jarrard** [comment]
Well you'd need the Chinese Matrix Package I believe. But then you will be forced to change to Chinese store which is restricted.. I suggest using Global login and just change language to Chinese.

**Comment by hirosichen** [comment]
Thanks. Is it possible to change to Chinese store? I wanted to download
those games available in Chinese store. In that case, would that be
possible that I can switch back to Global store?

**Comment by jarrard** [comment]
Sure there is a store apk for global and chinese I believe in this very github. And instructions. 

Once you install the game from Chinese store it should remain in your library after you switch to global again.. but you'll be needing both a Chinese and Global user account so who knows how well that will work.

**Comment by hirosichen** [comment]
Thanks Jarrad. The issues I am facing right now is I cannot login via my
China account. It's always shown in email login, which is for global users.
Do you have any idea in this regard? Thank you :)

jarrard ***@***.***> 於 2022年12月4日 週日 上午11:07 寫道：

**Comment by jarrard** [comment]
Sounds like you've skipped over a few steps to me, such as the region change command and installing the chinese apks back on.

**Comment by hirosichen** [comment]
Thanks. I got this message when I clicked 3.切换至中国区.bat Does anyone face the
same issue?

C:\Users\chyed\Downloads\PicoAreaHelper-main\\Apks\China\com.bytedance.pico.matrix_5.1.1.apk
Performing Streamed Install
adb: failed to install
C:\Users\chyed\Downloads\PicoAreaHelper-main\\Apks\China\com.bytedance.pico.matrix_5.1.1.apk:
Failure [INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed to collect
certificates from /data/app/vmdl1587336758.tmp/base.apk: Failed reading
lib/armeabi-v7a/libEncryptor.so in ***@***.***:
META-INF/MANIFEST.MF has invalid digest for lib/armeabi-v7a/libEncryptor.so
in lib/armeabi-v7a/libEncryptor.so]

**Comment by jarrard** [comment]
I'm sorry mate I'm not really the author of this github nor am I experience in converting headsets to Chinese. 

Either way I'd digest the scripts manually and issue the commands in console/cmd prompt manually so you get a understand of what is being done. Also you may need to factory reset the headset just to switch it to Chinese headset.  

IMO the whole process is really not worth it unless you wish to loose global functionality all together until you reset headset. 

Pico haven't made this headset particularly easy to develop for IMO and targeting separated markets.

**Comment by jarrard** [comment]
Additionally I'll update the first post if a proper fix for the Friends and Pico-Fit apps can be found (so they don't reset after device reboot) OR a FULL complete Rom Flash to Global is found.

One thing for sure is I probably can't rely on that owomushi guy for specific reasons I won't go into here.

**Comment by ooBadgeroo** [comment]
> Additionally I'll update the first post if a proper fix for the Friends and Pico-Fit apps can be found (so they don't reset after device reboot) OR a FULL complete Rom Flash to Global is found.
> 
> One thing for sure is I probably can't rely on that owomushi guy for specific reasons I won't go into here.

Thanks... appreciate  your efforts ...

**Comment by jarrard** [comment]
Solution to convert headsets to full global found by owomushi in the end, so guess I was wrong.  Didn't think he'd find a way.

Here is his latest video about it. 

MY HEADSET needed the NON-OEM update zip so if the normal one isn't found (update unavailable) then try the non-oem zips.

https://www.youtube.com/watch?v=Kzwrj4lXxVc

Thread closed.
