### ISSUE TITLE
找不到PICO设备，请检查数据线连接是否正常，设备是否已打开开发者模式！ 请按任意键继续. . .

### ISSUE THREAD

**Issue by cancundeyingzi** [CMoyuer/PicoAreaHelper#3]
===================================================
PICO区域切换助手
版本：1.0.2
By：如梦Nya
* daemon not running; starting now at tcp:5037
could not read ok from ADB Server
* failed to start daemon
adb.exe: failed to check server version: cannot connect to daemon
===================================================
找不到PICO设备，请检查数据线连接是否正常，设备是否已打开开发者模式！
请按任意键继续. . .

反复确认电脑已经识别到pico,反复确认开启开发者选项以及usb调试,已安装驱动

小米手机刷机正常运行

**Comment by CMoyuer** [comment]
看提示是因为ADB端口被占用了
可以新建环境变量ANDROID_ADB_SERVER_PORT，值是5038或者未占用端口，再重新打开

**Comment by cancundeyingzi** [comment]
> 看提示是因为ADB端口被占用了 可以新建环境变量ANDROID_ADB_SERVER_PORT，值是5038或者未占用端口，再重新打开

===================================================
PICO区域切换助手
版本：1.0.2
By：如梦Nya
===================================================
准备切换设备区域到：全球
请确保过程中不要拔掉数据线
设置完成后设备会自动重启，敬请留意
===================================================
请按任意键继续. . .

应该正常了

**Comment by cancundeyingzi** [comment]
目前遇到的几个问题(海外转中国)
1炸鸡,安卓系统炸鸡,打不开了,进rec..重启概率解决,不行只能fastboot
2进去之后输入账号还是只能邮箱,不能手机登录.重刷一遍概率解决.
3繁体,,没找到好方法,,国家吗已经是cn了

**Comment by CMoyuer** [comment]
抱歉好久没看Issues，现在问题解决了吗？

**Comment by CMoyuer** [comment]
提醒一下，如果要升级系统的话，之前用指令行切换过区域的话请留意用同样的方式切换回国区，不然有几率会变砖（B站已经有老哥中招了）
保险起见是切换一下其他区，再切一下国区
